"""Song and job records: queries, serialization, quota accounting and job creation."""

from __future__ import annotations

import json
import logging
import os
import sqlite3
from pathlib import Path

from . import db
from .config import FORMAT_BYTES_PER_SEC, FORMAT_EXT, Config
from .util import video_url

log = logging.getLogger("yt_library")

MEDIA_TYPES = {"mp3": "audio/mpeg", "m4a": "audio/mp4", "aac": "audio/aac", "opus": "audio/ogg",
               "ogg": "audio/ogg", "wav": "audio/wav", "flac": "audio/flac"}
ACTIVE = ("queued", "running")
UNKNOWN_DURATION = 600  # seconds assumed for the quota estimate when yt-dlp gives none


class QuotaExceeded(Exception):
    pass


# ---- songs --------------------------------------------------------------------

SONG_SELECT = """SELECT s.*, p.title AS parent_title FROM songs s
                 LEFT JOIN songs p ON p.id = s.parent_id"""


def song_dict(row: sqlite3.Row) -> dict:
    return {
        "id": row["id"], "video_id": row["video_id"], "title": row["title"],
        "uploader": row["uploader"], "duration": row["duration"], "format": row["format"],
        "ext": row["ext"], "size": row["size"], "created_at": row["created_at"],
        "expires_at": row["expires_at"], "source_url": row["source_url"],
        "parent_id": row["parent_id"], "parent_title": row["parent_title"],
        "file_url": f"/api/songs/{row['id']}/file",
        "download_url": f"/api/songs/{row['id']}/file?download=1",
    }


def list_songs(conn) -> list[dict]:
    rows = conn.execute(SONG_SELECT + " WHERE s.expires_at > ? ORDER BY s.created_at DESC, s.id DESC",
                        (db.now(),)).fetchall()
    return [song_dict(r) for r in rows]


def get_song(conn, song_id: int) -> sqlite3.Row | None:
    return conn.execute(SONG_SELECT + " WHERE s.id = ? AND s.expires_at > ?", (song_id, db.now())).fetchone()


def song_path(cfg: Config, row) -> Path:
    # filenames are generated by us (<video_id>.<ext> etc.), never taken from users
    return cfg.library_dir / Path(row["filename"]).name


def delete_songs(cfg: Config, conn, ids: list[int]) -> int:
    n = 0
    for sid in ids:
        with db.tx(conn):
            row = conn.execute("SELECT * FROM songs WHERE id = ?", (sid,)).fetchone()
            if not row:
                continue
            conn.execute("DELETE FROM songs WHERE id = ?", (sid,))
            remove_quietly(song_path(cfg, row))
        n += 1
    return n


def extend_songs(cfg: Config, conn, ids: list[int], seconds: int) -> None:
    now = db.now()
    new = now + min(seconds, cfg.max_lifetime)
    with db.tx(conn):
        conn.executemany("UPDATE songs SET expires_at = MAX(expires_at, ?) WHERE id = ? AND expires_at > ?",
                         [(new, i, now) for i in ids])


def find_duplicate(conn, video_id: str, fmt: str):
    return conn.execute(
        "SELECT * FROM songs WHERE video_id = ? AND format = ? AND parent_id IS NULL AND expires_at > ?",
        (video_id, fmt, db.now())).fetchone()


def existing_by_video(conn, video_ids: list[str]) -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = {}
    now = db.now()
    for vid in set(video_ids):
        for r in conn.execute("SELECT id, format FROM songs WHERE video_id = ? AND parent_id IS NULL "
                              "AND expires_at > ?", (vid, now)):
            out.setdefault(vid, []).append({"song_id": r["id"], "format": r["format"]})
    return out


def filename_for(fmt: str, video_id: str) -> str:
    # alac and m4a both use .m4a, so alac gets a suffix to keep one file per (video, format)
    ext = FORMAT_EXT[fmt]
    return f"{video_id}-alac.{ext}" if fmt == "alac" else f"{video_id}.{ext}"


# ---- quota --------------------------------------------------------------------

def used_bytes(conn) -> int:
    return conn.execute("SELECT COALESCE(SUM(size), 0) FROM songs").fetchone()[0]


def reserved_bytes(conn) -> int:
    tracks = conn.execute(
        "SELECT COALESCE(SUM(t.estimate), 0) FROM tracks t JOIN jobs j ON j.id = t.job_id "
        "WHERE j.status IN ('queued', 'running') AND t.status IN ('pending', 'running')").fetchone()[0]
    edits = conn.execute("SELECT COALESCE(SUM(estimate_bytes), 0) FROM jobs "
                         "WHERE kind = 'edit' AND status IN ('queued', 'running')").fetchone()[0]
    return tracks + edits


def estimate(fmt: str, duration: float | None) -> int:
    return int((duration or UNKNOWN_DURATION) * FORMAT_BYTES_PER_SEC[fmt])


def check_quota(cfg: Config, conn, extra: int) -> None:
    used, reserved = used_bytes(conn), reserved_bytes(conn)
    if used + reserved + extra > cfg.storage_quota:
        free = max(0, cfg.storage_quota - used - reserved)
        raise QuotaExceeded(
            f"Not enough storage: this needs about {_mb(extra)}, but only {_mb(free)} of the "
            f"{_mb(cfg.storage_quota)} quota is free (including queued jobs). Delete songs or wait "
            f"for some to expire, then try again.")


def _mb(n: int) -> str:
    return f"{n / 1024**3:.1f} GB" if n >= 1024**3 else f"{n / 1024**2:.0f} MB"


# ---- jobs ---------------------------------------------------------------------

def job_dict(conn, row: sqlite3.Row, with_tracks: bool = True) -> dict:
    d = {k: row[k] for k in ("id", "kind", "status", "url", "format", "lifetime", "title", "created_at",
                             "started_at", "finished_at", "error", "result_song_id")}
    d["single"] = bool(row["single"])
    d["song_id"] = row["song_id"]
    d["preview_url"] = f"/api/previews/{row['id']}" if row["kind"] == "preview" and row["status"] == "done" else None
    d["queue_position"] = None
    if row["status"] == "queued":
        lane = ("preview",) if row["kind"] == "preview" else ("download", "edit")
        q = ",".join("?" * len(lane))
        d["queue_position"] = conn.execute(
            f"SELECT COUNT(*) FROM jobs WHERE status IN ('queued','running') AND kind IN ({q}) AND id <= ?",
            (*lane, row["id"])).fetchone()[0]
    d["tracks"] = []
    if with_tracks:
        d["tracks"] = [
            {"index": t["idx"], "video_id": t["video_id"], "title": t["title"], "duration": t["duration"],
             "status": t["status"], "error": t["error"], "song_id": t["song_id"]}
            for t in conn.execute("SELECT * FROM tracks WHERE job_id = ? ORDER BY idx", (row["id"],))]
    return d


def list_jobs(conn) -> list[dict]:
    rows = conn.execute(
        "SELECT * FROM jobs WHERE kind != 'preview' AND status IN ('queued','running') "
        "UNION ALL SELECT * FROM (SELECT * FROM jobs WHERE kind != 'preview' "
        "AND status NOT IN ('queued','running') ORDER BY id DESC LIMIT 50) ORDER BY id DESC").fetchall()
    return [job_dict(conn, r) for r in rows]


def count_queued(conn) -> int:
    return conn.execute("SELECT COUNT(*) FROM jobs WHERE status = 'queued' AND kind != 'preview'").fetchone()[0]


def create_download_job(cfg: Config, conn, url: str, title: str, fmt: str, lifetime: str,
                        single: bool, entries: list[dict], client_ip: str) -> int:
    """Insert a queued download job with one pending track per entry (checked for quota)."""
    now = db.now()
    with db.tx(conn):
        tracks, need = [], 0
        for e in entries:
            status, error, song_id, est = "pending", None, None, 0
            if e["duration"] is not None and e["duration"] > cfg.max_track_duration:
                status = "skipped"
                error = f"longer than the {cfg.max_track_duration // 60} minute limit"
            else:
                dup = find_duplicate(conn, e["video_id"], fmt)
                if dup is None:
                    est = estimate(fmt, e["duration"])
                    need += est
            tracks.append((e, status, error, song_id, est))
        check_quota(cfg, conn, need)
        cur = conn.execute(
            "INSERT INTO jobs (kind, status, url, format, lifetime, single, title, client_ip, created_at) "
            "VALUES ('download', 'queued', ?, ?, ?, ?, ?, ?, ?)",
            (url, fmt, lifetime, int(single), title, client_ip, now))
        job_id = cur.lastrowid
        conn.executemany(
            "INSERT INTO tracks (job_id, idx, video_id, title, uploader, duration, status, estimate, error, song_id) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            [(job_id, i, e["video_id"], e["title"], e["uploader"], e["duration"], st, est, err, sid)
             for i, (e, st, err, sid, est) in enumerate(tracks, start=1)])
    return job_id


def create_edit_job(cfg: Config, conn, kind: str, song, params: dict, client_ip: str) -> int:
    with db.tx(conn):
        est = 0
        if kind == "edit":
            est = int(song["size"] or 0) + 1024 * 1024
            check_quota(cfg, conn, est)
        cur = conn.execute(
            "INSERT INTO jobs (kind, status, url, format, title, params, song_id, client_ip, estimate_bytes, "
            "created_at) VALUES (?, 'queued', ?, ?, ?, ?, ?, ?, ?, ?)",
            (kind, song["source_url"], song["format"], song["title"], json.dumps(params), song["id"],
             client_ip, est, db.now()))
        return cur.lastrowid


def source_url_for(video_id: str) -> str:
    return video_url(video_id)


def remove_quietly(path: Path) -> None:
    try:
        os.unlink(path)
    except FileNotFoundError:
        pass
